name: adt
description: A code generator for algebraic data types such as immutable data classes with copyWith method and immutable discriminated unions with pattern matching. They compare as value types.
version: 0.5.0+6
homepage: https://github.com/vr19860507/adt

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  meta: ^1.0.0
  build: ^1.0.0
  analyzer: ^0.41.0
  code_builder: ^3.0.0
  source_gen: ^0.9.0
  dart_style: ^1.0.0
  adt_annotation: ^0.3.0

dev_dependencies:
  strict_analyzer: ^0.6.0